name: Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest 790762402500.dkr.ecr.us-east-2.amazonaws.com/frontend:latest

      - name: Push Frontend Image
        run: |
          docker push 790762402500.dkr.ecr.us-east-2.amazonaws.com/frontend:latest

      - name: Build Backend Image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest 790762402500.dkr.ecr.us-east-2.amazonaws.com/backend:latest

      - name: Push Backend Image
        run: |
          docker push 790762402500.dkr.ecr.us-east-2.amazonaws.com/backend:latest

      - name: Force ECS Frontend Deployment
        run: |
          aws ecs update-service \
            --cluster ecs-prod-cluster-2 \
            --service frontend-service \
            --force-new-deployment

      - name: Force ECS Backend Deployment
        run: |
          aws ecs update-service \
            --cluster ecs-prod-cluster-2 \
            --service backend-service \
            --force-new-deployment